"""empty message

Revision ID: 07719dd2e96e
Revises: 214f0d905151
Create Date: 2022-03-06 16:18:04.789718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07719dd2e96e'
down_revision = '214f0d905151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
